### ISSUE TITLE
Usage with private git repo

### ISSUE THREAD

**Issue by sporto** [HashNuke/ansible-elixir-stack#11]
When trying to use this with a private repo I get:

```
TASK: [HashNuke.elixir-stack | clone project] *********************************
failed: [128.199.129.15] => {"cmd": "/usr/bin/git ls-remote '' -h refs/heads/master", "failed": true, "rc": 128}
stderr: Warning: Permanently added the RSA host key for IP address '131.103.20.167' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
```

This makes sense as I have not given access to the git repo to the deployer user.

Somewhere in the workflow I need to create and upload ssh keys for the deployer user, then copy the public key in repository.

Thoughts on this?

**Comment by HashNuke** [comment]
Actually that should work as is. Your SSH keys are forwarded from localhost by Ansible. I forgot to document that ssh-add has to be used to add the key locally to ssh-agent before using private repos. I'll do it first thin I wake up.

**Comment by HashNuke** [comment]
Assuming id_rsa is the name of your ssh key, run `ssh-add ~/.ssh/id_rsa` once everytime you start your computer. It'll run fine.

**Comment by HashNuke** [comment]
I've updated docs with this info. Thanks for reporting this issue @sporto.
