### ISSUE TITLE
Nginx conf created does not route web socket requests properly, it proxies it as http:// instead of ws://

### ISSUE THREAD

**Issue by zabirauf** [HashNuke/ansible-elixir-stack#7]

**Comment by HashNuke** [comment]
@zabirauf yes. There's no config for websockets yet. I just started building an app with websockets.
If you have a config please do send a PR. I'll merge it.

This is the template that needs editing: https://github.com/HashNuke/ansible-elixir-stack/blob/master/templates/app.nginx.j2

**Comment by zabirauf** [comment]
Adding the following works

```
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
```

But this will set the `Upgrade` & `Connection` header values for the HTTP requests as well. I couldn't find a way of setting it based on wether its HTTP request or WS request apart from creating another `location` for that websocket route, though i also didn't look very very hard :). But it works fine. If you don't have any issues with that then I'll make the change and send the PR.

**Comment by HashNuke** [comment]
@zabirauf Aren't most websocket channels at specific endpoints? I'm not sure if a generic solution is better. If you can give me a couple days time I'll read up on this and make the changes.

**Comment by zabirauf** [comment]
Yep, they have different routes. If we want to add it based on various routes then I guess we have to read the routes in routers.ex and see which are websocket ones to create a corresponding `location` with those headers set. I agree, generic solution is not the best idea, more research is required for a better solution.

**Comment by HashNuke** [comment]
@zabirauf Was bothered about separate `location` directives because that way everytime the websocket endpoints change, the setup script has to be run. It's a hassle. I just checked Heroku's docs. They seem to be using a generic solution too.

Please go ahead and send a PR for the generic solution.
